add  user friend list with validation
delowarsikder/Friends-App pull request #1
Opened 2022-09-20 07:10 UTC by delowarsikder

user can access his own friend list. User id show in nav bar

2022-09-20 07:22 UTC, saadrumon requested changes

2022-09-20 07:22 UTC, saadrumon commented on app/controllers/friends_controller.rb
> +    # @friends = Friend.all
@delowarsikder please remove commented code

2022-09-20 07:22 UTC, saadrumon commented on app/controllers/friends_controller.rb
> +  before_action :correct_user, only: [:show, :edit, :update, :destroy]
@delowarsikder This before method is unnecessary

2022-09-20 07:22 UTC, saadrumon commented on app/controllers/friends_controller.rb
> +  end
@delowarsikder this method is unnecessary

2022-09-20 07:22 UTC, saadrumon commented on app/views/home/_header.html.erb
> +        </li>
@delowarsikder please remove the redundant sign-out option.

2022-09-23 12:38 UTC, delowarsikder commented
This PR is not required anymore.

2022-09-23 12:38 UTC, closed without merging